config/routes.rb
Rails.application.routes.draw do
	root to: 'volunteers#index'
	devise_for :admins
	get '/groups/:id/volunteers' => 'groups#show_volunteers',as: 'show_volunteers'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :volunteers,only: [:index, :show]
	resources :groups,only: [:new, :index, :create, :show, :edit, :destroy, :update]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
	
	has_many :volunteers
	attachment :image
	validates :name, uniqueness: true, presence: true, length: { in: 2..100 }
	validates :address, presence: true
	validates :active_area, presence: true
	validates :description, presence: true

	# 求人募集情報との紐付けを行う
	def connect_volunteers(group_name, group_id)
		volunteers = Volunteer.where(group_name: group_name)
    	volunteers.each do |volunteer|
    		volunteer.group_id = group_id
    		volunteer.save
    	end
	end

	# 求人募集情報との紐付け解除を行う
	def disconnect_volunteers(group_volunteers)
		volunteers = group_volunteers
		volunteers.each do |volunteer|
			volunteer.group_id = nil
			volunteer.save
		end
	end

end

app/models/volunteer.rb
class Volunteer < ApplicationRecord

	belongs_to :group, optional: true
	validates :title, presence: true
	validates :group_name, presence: true
	validates :event_url, presence: true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
    def after_sign_in_path_for(resource_or_scope)
		groups_path
 	end

 	def after_sign_out_path_for(resource)
    	new_admin_session_path
    end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :authenticate_admin!, only: [:new, :edit, :destroy]

	def index
		@groups = Group.page(params[:page]).reverse_order
	end

	def show
		@group = Group.find(params[:id])
	end

	def new
		@group = Group.new
	end

	def edit
		@group = Group.find(params[:id])
	end

	def create
		@group=Group.new(group_params)
	    if @group.save
	    	flash[:notice] = "Registered group information."
      		@group.connect_volunteers(params[:group][:name], @group.id)
	    	redirect_to groups_path
	    else
	    	render :new
	    end
	end

	def update
		@group = Group.find(params[:id])
		group_old_name = @group.name
		if @group.update(group_params)
			if group_old_name != @group.name
				@group.disconnect_volunteers(@group.volunteers)
				@group.connect_volunteers(params[:group][:name], @group.id)
			end
			flash[:notice] = "Updated Group information."
			redirect_to group_path(@group.id)
		else
			render :edit
		end
	end

	def destroy
		group = Group.find(params[:id])
		group.disconnect_volunteers(group.volunteers)
		group.destroy
		redirect_to groups_path
	end

	def show_volunteers
		@group = Group.find(params[:id])
		@volunteers = @group.volunteers
	end

	private

	def group_params
		params.require(:group).permit(:name,:active_area,:address,:mail,:phone_number,:description,:image)
	end

end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController

      def index
          @volunteers = Volunteer.where.not(group_id: nil).page(params[:page]).reverse_order
      end

      def show
          @volunteer = Volunteer.find(params[:id])
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/groups/_form.html.erb
<%= form_for(group) do |f| %>
	<div class="field row">
		<label>団体名</label>
		<%= f.text_field :name, class: "input_params", placeholder: "団体名を入力してください(必須)" %>
	</div>
	<div class="field row">
		<label>住所</label>
		<%= f.text_field :address, class: "input_params", placeholder: "住所を入力してください(必須)" %>
	</div>
	<div class="field row">
		<label>電話番号</label>
		<%= f.text_field :phone_number, class: "input_params", placeholder: "電話番号を入力してください(ハイフンなし)" %>
	</div>
	<div class="field row">
		<label>e-mail</label>
		<%= f.text_field :mail, class: "input_params", placeholder: "メールアドレスを入力してください" %>
	</div>
	<div class="field row">
		<label>活動エリア</label>
		<%= f.text_field :active_area, class: "input_params", placeholder: "活動エリアを入力してください(必須)" %>
	</div>
	<div class="field row">
		<label>団体概要</label>
		<%= f.text_area :description, class: "input_params", rows:"4", placeholder: "団体概要(必須)" %>
	</div>
	<div class="field row">
		<div class="col-xs-4"></div>
		<div class="col-xs-4">
			<label>風景画像</label>
			<%= f.attachment_field :image, placeholder: "風景画像",class: "image" %>
		</div>
		<div class="col-xs-4"></div>
	</div>
	<div class="actions row">
	 	<%= f.submit "登録する" ,class: "button" %>
	</div>
<% end %>

app/views/groups/edit.html.erb
<h1 class="group_new">団体登録</h1>
<div>
	<%= render 'layouts/errors', obj: @group %>
</div>
<div class="form">	
	<%= render 'groups/form', group: @group %>
</div>

app/views/groups/index.html.erb
<p class="groups">登録団体一覧</p>
<table class="table table-hover table-inverse">
 	<thead>
   		<tr> 
    	  	<th>団体名</th>
    	  	<th>住所</th>
    	  	<th>電話番号</th>
    	  	<th>メールアドレス</th>
    	  	<th></th>
    	  	<th></th>
    	  	<th></th>
    	</tr>
  	</thead>
	<% @groups.each do |group| %>
		<tbody>
		    <tr>
		    	<td>
		    		<%= group.name %>
		    	</td>
		    	<td>
		    		<%= group.address %>
		    	</td>
		    	<td>
		    		<%= group.phone_number %>
		    	</td>
		    	<td>
		    		<%= group.mail %>
		    	</td>
		    	<td>
		    		<%= link_to "詳細へ", group_path(group.id) %>
		    	</td>
		    	<td>
		    		<%= link_to "編集へ", edit_group_path(group.id) %>
		    	</td>
		    	<td>
		    		<% if group.volunteers.exists? %>
		    			<%= link_to "求人", show_volunteers_path(group.id) %>
		    		<% end %>
		    	</td>
		    </tr>
		</tbody>
	<% end %>
	<%= paginate @groups %>
</table>

app/views/groups/new.html.erb
<h1 class="group_new">団体登録</h1>
<div>
	<%= render 'layouts/errors', obj: @group %>
</div>
<div class="form">	
	<%= render 'groups/form', group: @group %>
</div>

app/views/groups/show.html.erb
<h1 class="event_show">登録団体詳細</h1>
<div class="image_show">
	<%= attachment_image_tag @group, :image, format: 'jpeg', class: "attachment user profile_image fallback", fallback: "no_image.jpg", size: "300x200"  %>
</div>
<div class="row">
    <p class="object">団体者名</p>
	<%= @group.name %>
</div>
<div class="row">
    <p class="object">住所</p>
	<%= @group.address %>
</div>
<div class="row">
    <p class="object">電話番号</p>
    <%= @group.phone_number%>
</div>
<div class="row">
    <p class="object">メールアドレス</p>
	<%= @group.mail %>
</div>
<div class="row">
    <p class="object">活動エリア</p>
    <%= @group.active_area %>
</div>
<div class="row">
    <p class="object">団体概要</p>
    <%= @group.description %>
</div>
<% if admin_signed_in? %>
    <div class="delete">
        <%= link_to "編集画面へ", edit_group_path(@group.id), class: "green-button"%>
        <%= link_to "削除する", group_path(@group.id), method: :delete, data: {confirm: "この団体を本当に削除してよろしいでしょうか。"}, class: "delete-button"%>
    </div>
<% end %>
<div>
    <%= link_to "一覧画面へ戻る", groups_path %>
</div>

app/views/groups/show_volunteers.html.erb
<p class="title"><%= @group.name %>の求人募集一覧</p>
<%= render 'volunteers/index', volunteers: @volunteers %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
    <div id="error_explanation">
      <h3><%= obj.errors.count %> 件のエラーがあります：</h3>

      <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <span>ボランティア求人サイト</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if admin_signed_in? %>
          <li><%= link_to '登録団体一覧画面', groups_path, class: 'glyphicon' %></li>
          <li><%= link_to '団体登録画面', new_group_path, class: 'glyphicon' %></li>
          <li><%= link_to 'ボランティア求人一覧画面', volunteers_path , class: 'glyphicon'%></li>
          <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'glyphicon' %></li>
        <% else %>
          <li><%= link_to '登録団体一覧画面', groups_path, class: 'glyphicon' %></li>
          <li><%= link_to 'ボランティア求人一覧画面', volunteers_path, class: 'glyphicon' %></li>
          <li><%= link_to 'ログイン', new_admin_session_path , class: 'glyphicon'%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScrapingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="body">
      <div class='container'>
        <div class="col-xs-1"></div>
        <div class="col-xs-10">
          <p id="notice"><%= notice %></p>
          <%= yield %>
        </div>
        <div class="col-xs-1"></div>
      </div>
  </div>
  </body>
</html>

app/views/volunteers/_index.html.erb
<table class="table table-hover table-inverse">
 	<thead>
   		<tr> 
   			<th></th>
    	  	<th>タイトル</th>
    	  	<th>開催日時</th>
    	  	<th>主催者名</th>
    	  	<th>     </th>
    	</tr>
  	</thead>
	<% volunteers.each do |volunteer| %>
			<tbody>
			    <tr>
			    	<td>
			    		<%= image_tag "#{volunteer.image_id}", size:"120x80" %>
			    	</td>
			    	<td>
			    		<%= volunteer.title %>
			    	</td>
			    	<td>
			    		<%= volunteer.date %><%= volunteer.open_time %>
			    	</td>
			    	<td>
			    		<%= volunteer.group_name %>
			    	</td>
			    	<td>
			    		<%= link_to "詳細へ", volunteer_path(volunteer.id) %>
			    	</td>
			    </tr>
			</tbody>
	<% end %>
</table>

app/views/volunteers/index.html.erb
<p class="title">ボランティア一覧</p>
<%= render 'volunteers/index', volunteers: @volunteers %>
<%= paginate @volunteers %>

app/views/volunteers/show.html.erb
<h1 class="event_show">イベント詳細</h1>
<div class="image_show">
	<%= image_tag "#{@volunteer.image_id}", size:"300x200" %>
</div>
<div class="row">
    <p class="object">タイトル</p>
	<%= @volunteer.title %>
</div>
<div class="row">
    <p class="object">説明</p>
	<%= @volunteer.description %>
</div>
<div class="row">
    <p class="object">開催場所</p>
    <%= @volunteer.venue %>
</div>
<div class="row">
    <p class="object">開催日時</p>
	<%= @volunteer.date %><%= @volunteer.open_time %>
</div>
<div class="row">
    <p class="object">主催者名</p>
    <%= @volunteer.group_name %>
</div>
<div class="row">
    <%= link_to "イベントURL(詳細はこちら)", @volunteer.event_url %>
</div>